### PR TITLE
Changed build tools version to 25.

### PR DESCRIPTION
**Pull request by Vookash**

### CODE REVIEW

**Comment by hardysim** [comment]
I think it would be good to update all variables to 25, especially `VERSION_TARGET_SDK`. I'm using this image but trying to use `com.android.support:design:25.0.1` which is currently missing.

@showcheap can you update / merge this?

**Review by suciptoid — APPROVED** [review]

**Comment by suciptoid** [comment]
Thanks @Vookash & @hardysim 👍

**Comment by Vookash** [comment]
@hardysim You're right. I just didn't think about that.

Maybe we should set `VERSION_SDK_TOOLS` 25.2.3, `VERSION_BUILD_TOOLS` 25.0.1 and `VERSION_TARGET_SDK` 25?

Or maybe can this parameters be set dynamically from GitLab CI file?

**Comment by hardysim** [comment]
I tried it yesterday with `VERSION_SDK_TOOLS = 25.2.3` (which is the current version you see in the SDK-manager) but it doesn't work. You'll get an error while downloading the `tools_r${VERSION_SDK_TOOLS}-linux.zip`-file.

But it seems to work with the 24-version as well (as we have the 25-SDK you can build just fine).

**Comment by suciptoid** [comment]
Hi @hardysim, try my new image on gitlab https://gitlab.com/showcheap/android-ci
Updated to
Target SDK 24
Build Tools version 25.0.1

**Comment by hardysim** [comment]
@showcheap hehe, nice. I just created my own one, too ;-)

Because the script downloads the lastest supportLib on build-time, you'll need to re-run a build when there's a new supportLib-version (but build-tools etc. didn't change).

---

Is this repo deprecated then (you switched to GitLab)?

**Comment by suciptoid** [comment]
@hardysim Yes, maybe this repo no longer updated. Move to Gitlab registry :D
Maybe I still re-mirror to Github for a new script from Gitlab.

**Pull request merged**
